=== Bloodymorphe/Silverpeas-Core/web-core/test/resources/com/silverpeas/workflow/tests/processModel.xsd
<?xml version="1.0" encoding="UTF-8"?>
<!-- edited with XML Spy v4.2 U (http://www.xmlspy.com) by Ludovic Bertin (-) -->
<!--W3C Schema generated by XML Spy v4.2 U (http://www.xmlspy.com)-->
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" elementFormDefault="qualified">
	<!-- .......................................... DEFINITION DE MODÃˆLE DE PROCEDURE -->
	<xs:element name="processModel">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="label" minOccurs="0" maxOccurs="unbounded"/>
				<xs:element ref="description" minOccurs="0" maxOccurs="unbounded"/>
				<xs:element ref="roles"/>
				<xs:element ref="presentation"/>
				<xs:element ref="participants"/>
				<xs:element ref="states"/>
				<xs:element ref="actions"/>
				<xs:element ref="userInfos"/>
				<xs:element ref="dataFolder"/>
				<xs:element ref="forms"/>
			</xs:sequence>
			<xs:attribute name="name" type="xs:string" use="required"/>
		</xs:complexType>
	</xs:element>
	<!-- ................................................................. DEFINITION D'UN ROLE -->
	<xs:element name="role">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="label" maxOccurs="unbounded"/>
				<xs:element ref="description" minOccurs="0" maxOccurs="unbounded"/>
			</xs:sequence>
			<xs:attribute name="name" type="xs:ID" use="required"/>
		</xs:complexType>
	</xs:element>
	<!-- ................................................................. DEFINITION D'UN PARTICIPANT -->
	<xs:element name="participant">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="label" minOccurs="0" maxOccurs="unbounded"/>
				<xs:element ref="description" minOccurs="0" maxOccurs="unbounded"/>
			</xs:sequence>
			<xs:attribute name="name" type="xs:ID"/>
			<xs:attribute name="resolvedState" type="xs:string"/>
		</xs:complexType>
	</xs:element>
	<!-- ................................................................. DEFINITION D'UNE ACTION -->
	<xs:element name="action">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="label" minOccurs="0" maxOccurs="unbounded"/>
				<xs:element ref="description" minOccurs="0" maxOccurs="unbounded"/>
				<xs:element ref="allowedUsers" minOccurs="0"/>
				<xs:element ref="consequences" minOccurs="0"/>
			</xs:sequence>
			<xs:attribute name="name" type="xs:ID" use="required"/>
			<xs:attribute name="form" type="xs:IDREF" use="required"/>
			<xs:attribute name="kind" type="xs:string" default="update"/>
		</xs:complexType>
	</xs:element>
	<!-- ...................................................................... DEFINITION D'UN LABEL -->
	<xs:element name="label">
		<xs:complexType>
			<xs:simpleContent>
				<xs:extension base="xs:string">
					<xs:attribute name="lang" type="xs:string" default="default"/>
					<xs:attribute name="role" type="xs:string" default="default"/>
				</xs:extension>
			</xs:simpleContent>
		</xs:complexType>
	</xs:element>
	<!-- ...................................................................... DEFINITION D'UNE ACTIVITE-->
	<xs:element name="activity">
		<xs:complexType>
			<xs:simpleContent>
				<xs:extension base="xs:string">
					<xs:attribute name="lang" type="xs:string" default="default"/>
					<xs:attribute name="role" type="xs:string" default="default"/>
				</xs:extension>
			</xs:simpleContent>
		</xs:complexType>
	</xs:element>
	<!-- ...................................................................... DEFINITION D'UNE DESCRIPTION-->
	<xs:element name="description">
		<xs:complexType>
			<xs:simpleContent>
				<xs:extension base="xs:string">
					<xs:attribute name="lang" type="xs:string" default="default"/>
					<xs:attribute name="role" type="xs:string" default="default"/>
				</xs:extension>
			</xs:simpleContent>
		</xs:complexType>
	</xs:element>
	<!-- ...................................................................... DEFINITION D'UN TITRE-->
	<xs:element name="title">
		<xs:complexType>
			<xs:simpleContent>
				<xs:extension base="xs:string">
					<xs:attribute name="lang" type="xs:string" default="default"/>
					<xs:attribute name="role" type="xs:IDREFS"/>
				</xs:extension>
			</xs:simpleContent>
		</xs:complexType>
	</xs:element>
	<!-- ...................................................................... DEFINITION D'UN ETAT -->
	<xs:element name="state">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="label" minOccurs="0" maxOccurs="unbounded"/>
				<xs:element ref="activity" minOccurs="0" maxOccurs="unbounded"/>
				<xs:element ref="description" minOccurs="0" maxOccurs="unbounded"/>
				<xs:element ref="workingUsers" minOccurs="0"/>
				<xs:element ref="interestedUsers" minOccurs="0"/>
				<xs:element ref="allowedActions" minOccurs="0"/>
				<xs:element ref="preconditions" minOccurs="0"/>
			</xs:sequence>
			<xs:attribute name="name" type="xs:ID" use="required"/>
			<xs:attribute name="timeoutAction" type="xs:IDREF"/>
			<xs:attribute name="timeoutInterval" type="xs:string"/>
			<xs:attribute name="timeoutNotifyAdmin" type="xs:boolean" default="false"/>
		</xs:complexType>
	</xs:element>
	<!-- ...................................................................... DEFINITION D'UN FORMULAIRE -->
	<xs:element name="form">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="title" minOccurs="0" maxOccurs="unbounded"/>
				<xs:element name="input" minOccurs="0" maxOccurs="unbounded">
					<xs:complexType>
						<xs:sequence>
							<xs:element ref="label" minOccurs="0"/>
						</xs:sequence>
						<xs:attribute name="item" type="xs:IDREF"/>
						<xs:attribute name="value" type="xs:string"/>
						<xs:attribute name="readonly" type="xs:boolean" default="false"/>
					</xs:complexType>
				</xs:element>
			</xs:sequence>
			<xs:attribute name="name" type="xs:ID" use="required"/>
			<xs:attribute name="HTMLFileName" type="xs:string"/>
		</xs:complexType>
	</xs:element>
	<!-- ........................................................... DEFINITION DES DONNEES UTILISATEUR -->
	<xs:element name="userInfos">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="item" maxOccurs="unbounded"/>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	<!-- ...................................................................... DEFINITION D'UN DOSSIER -->
	<xs:element name="dataFolder">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="item" maxOccurs="unbounded"/>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	<!-- ...................................................................... DEFINITION D'UN ITEM -->
	<xs:element name="formula" type="xs:string"/>
	<xs:element name="readonly" type="xs:boolean"/>
	<xs:element name="type" type="xs:string"/>
	<xs:element name="item">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="label" minOccurs="0"/>
				<xs:element ref="description" minOccurs="0"/>
				<xs:element ref="type" minOccurs="0"/>
				<xs:element ref="readonly" minOccurs="0"/>
				<xs:element ref="formula" minOccurs="0"/>
			</xs:sequence>
			<xs:attribute name="name" type="xs:ID"/>
			<xs:attribute name="computed" type="xs:boolean" default="false"/>
			<xs:attribute name="mapTo" type="xs:string"/>
		</xs:complexType>
	</xs:element>
	<!-- ...................................................................... DEFINITION DES IMPACTS -->
	<xs:element name="kill" type="xs:boolean"/>
	<xs:element name="consequences">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="kill" maxOccurs="1"/>
				<xs:choice maxOccurs="unbounded">
					<xs:element name="set">
						<xs:complexType>
							<xs:attribute name="state" type="xs:IDREF" use="required"/>
						</xs:complexType>
					</xs:element>
					<xs:element name="unset">
						<xs:complexType>
							<xs:attribute name="state" type="xs:IDREF" use="required"/>
						</xs:complexType>
					</xs:element>
					<xs:element ref="notifiedUsers" minOccurs="0"/>
				</xs:choice>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	<!-- ...................................................................... DEFINITION DES UTILISATEURS CALCULES -->
	<xs:element name="relatedUser">
		<xs:complexType>
			<xs:attribute name="participant" type="xs:IDREF" />
			<xs:attribute name="folderItem" type="xs:IDREF" />
			<xs:attribute name="relation" type="xs:string"/>
			<xs:attribute name="role" type="xs:string"/>
		</xs:complexType>
	</xs:element>
	<!-- ...................................................................... DEFINITION DES UTILISATEURS NOTIFIES -->
	<xs:element name="notifiedUsers">
		<xs:complexType>
			<xs:choice>
				<xs:element ref="relatedUser" maxOccurs="unbounded"/>
			</xs:choice>
			<xs:attribute name="message" type="xs:string"/>
		</xs:complexType>
	</xs:element>
	<!-- ...................................................................... DEFINITION DES UTILISATEURS AFFECTES -->
	<xs:element name="workingUsers">
		<xs:complexType>
			<xs:choice>
				<xs:element ref="relatedUser" maxOccurs="unbounded"/>
				<xs:element ref="userInRole"/>
			</xs:choice>
			<xs:attribute name="role" type="xs:string"/>
		</xs:complexType>
	</xs:element>
	<!-- ...................................................................... DEFINITION DES UTILISATEURS IMPACTES -->
	<xs:element name="interestedUsers">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="relatedUser" maxOccurs="unbounded"/>
				<xs:element ref="userInRole" minOccurs="0"/>
			</xs:sequence>
			<xs:attribute name="role" type="xs:string"/>
		</xs:complexType>
	</xs:element>
	<!-- ...................................................................... DEFINITION D'UNE PRESENTATION -->
	<xs:element name="presentation">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="title" maxOccurs="unbounded"/>
				<xs:element ref="columns" maxOccurs="unbounded"/>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	<!-- ...................................................................... DEFINITION DES PRE-REQUIS A UNE ACTION -->
	<xs:element name="preconditions">
		<xs:complexType/>
	</xs:element>
	<!-- ...................................... DEFINITION D'UNE LISTE DE PERSONNES AYANT UN ROLE DONNE  -->
	<xs:element name="userInRole">
		<xs:complexType>
			<xs:attribute name="name" type="xs:string" use="required"/>
		</xs:complexType>
	</xs:element>
	<!-- .................................................... DEFINITION D'UNE LISTE D'ETATS -->
	<xs:element name="states">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="state" maxOccurs="unbounded"/>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	<!-- .................................................... DEFINITION D'UNE LISTE DE PARTICIPANTS -->
	<xs:element name="participants">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="participant" maxOccurs="unbounded"/>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	<!-- .................................................... DEFINITION D'UNE LISTE DE COLONNES -->
	<xs:element name="columns">
		<xs:complexType>
			<xs:sequence>
				<xs:element name="column" minOccurs="0" maxOccurs="unbounded">
					<xs:complexType>
						<xs:attribute name="item" type="xs:IDREF" use="required"/>
					</xs:complexType>
				</xs:element>
			</xs:sequence>
			<xs:attribute name="role" type="xs:string" use="required"/>
		</xs:complexType>
	</xs:element>
	<!-- .................................................... DEFINITION D'UNE LISTE DE FORMULAIRES -->
	<xs:element name="forms">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="form" maxOccurs="unbounded"/>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	<!-- .................................................... DEFINITION D'UNE LISTE D'ACTIONS AUTORISEES -->
	<xs:element name="roles">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="role" maxOccurs="unbounded"/>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	<!-- .................................................... DEFINITION D'UNE LISTE D'ACTIONS -->
	<xs:element name="actions">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="action" maxOccurs="unbounded"/>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	<!-- .................................................... DEFINITION D'UNE LISTE D'ACTIONS AUTORISEES -->
	<xs:element name="allowedActions">
		<xs:complexType>
			<xs:sequence>
				<xs:element name="allow" minOccurs="0" maxOccurs="unbounded">
					<xs:complexType>
						<xs:attribute name="action" type="xs:IDREF" use="required"/>
					</xs:complexType>
				</xs:element>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	<!-- .................................................... DEFINITION D'UNE LISTE DUTILISATEURS AUTORISES -->
	<xs:element name="allowedUsers">
		<xs:complexType>
			<xs:sequence>
				<xs:choice>
					<xs:element ref="userInRole"/>
					<xs:element ref="relatedUser" maxOccurs="unbounded"/>
				</xs:choice>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
</xs:schema>

=== Bloodymorphe/Silverpeas-Core/web-core/src/test/resources/com/silverpeas/workflow/tests/DemandeConges.xml
<?xml version="1.0" encoding="ISO-8859-1"?>

<!-- PROCÉDURE : DEMANDE DE CONGES -->

<processModel name="DemandeConges"
              xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
				  xsi:noNamespaceSchemaLocation="processModel.xsd">

	<label>Demande de congés</label>

	<!-- DESCRIPTION DES ROLES -->
	<roles>
		<role name="Employe">
			<label>Demandeur</label>
		</role>
		<role name="Responsable">
			<label>Responsable</label>
		</role>
		<role name="Secretaire">
			<label>Secrétaire</label>
		</role>
		<role name="supervisor">
			<label>Superviseur</label>
		</role>
	</roles>

	<!-- DEFINITION DES DONNEES UTILISATEUR -->
	<userInfos>
		<item name="departement" mapTo="position">
			<label>departement</label>
			<type>text</type>
		</item>
		<item name="secretaire">
			<label>Secrétaire</label>
			<type>user</type>
		</item>
		<item name="old_responsable">
			<label>Responsable</label>
			<type>user</type>
		</item>
	</userInfos>

	<!-- DEFINITION DU DOSSIER -->
	<dataFolder>
		<item name="nature">
			<label>Nature des congés</label>
			<type>text</type>
		</item>
		<item name="duree">
			<label>durée (nombre de jours ouvrés)</label>
			<type>text</type>
		</item>
		<item name="dateDebut">
			<label>Départ</label>
			<type>date</type>
		</item>
		<item name="dateFin">
			<label>Retour</label>
			<type>date</type>
		</item>
		<item name="commentaires">
			<label>Commentaires</label>
			<type>text</type>
		</item>
		<item name="responsable">
			<label>Responsable</label>
			<type>user</type>
		</item>
		<!--<item name="fichier">
			<label>Fichier</label>
			<type>file</type>
		</item>-->
	</dataFolder>

	<!-- PRESENTATION DES PROCEDURES EN COURS-->
	<presentation>
		<title role="Employe">
		    Congés du ${instance.dateDebut} au ${instance.dateFin}
		</title>
		<title role="Responsable">Demande de ${action.Creation.actor}</title>
		<title role="supervisor">Demande de ${action.Creation.actor}</title>
		<title role="Secretaire">Demande de ${action.Creation.actor}</title>
		<columns role="Employe">
			<column item="dateDebut"/>
			<column item="dateFin"/>
		</columns>
		<columns role="Responsable">
			<column item="dateDebut"/>
			<column item="dateFin"/>
		</columns>
		<columns role="Secretaire">
			<column item="dateDebut"/>
			<column item="dateFin"/>
		</columns>
	</presentation>

	<!-- DESCRIPTION DES PARTICIPANTS -->
	<participants>
		<participant name="Demandeur" state="" role="Employe">
			<label>Demandeur</label>
		</participant>
	</participants>

	<!-- DESCRIPTION DES ÉTATS -->
	<states>
		<state name="AttenteValidation">
			<label>En attente de validation</label>
			<workingUsers role="Responsable">
				<relatedUser folderItem="responsable"/>
			</workingUsers>
			<interestedUsers>
				<relatedUser participant="Demandeur" role="Employe"/>
			</interestedUsers>
			<allowedActions>
				<allow action="Accepter"/>
				<allow action="Refuser"/>
			</allowedActions>
		</state>

		<state name="Acceptee" timeoutAction="Supprimer" timeoutInterval="1">
			<label>Acceptée</label>
			<workingUsers role="Secretaire">
				<relatedUser participant="Demandeur" relation="secretaire"/>
			</workingUsers>
			<interestedUsers>
				<relatedUser participant="Demandeur" role="Employe"/>
			</interestedUsers>
			<allowedActions>
				<allow action="Valider"/>
			</allowedActions>
		</state>

		<state name="Traitee">
			<label>Acceptée et validée</label>
			<workingUsers role="Employe">
				<relatedUser participant="Demandeur"/>
			</workingUsers>
			<allowedActions>
				<allow action="Supprimer"/>
			</allowedActions>
		</state>

		<state name="Refusee">
			<label>Refusée</label>
			<workingUsers role="Employe">
				<relatedUser participant="Demandeur"/>
			</workingUsers>
			<allowedActions>
				<allow action="Supprimer"/>
			</allowedActions>
		</state>

	</states>

	<!-- DESCRIPTION DES ACTIONS -->
	<actions>
		<action name="Creation" form="creation" kind="create">
			<label>Création</label>
			<description>Création d'une nouvelle demande.</description>
			<allowedUsers>
				<userInRole name="Employe"/>
			</allowedUsers>
			<consequences>
				<consequence>
					<set state="AttenteValidation"/>
				</consequence>
			</consequences>
		</action>

		<action name="Accepter" form="acceptation">
			<label>Accepter</label>
			<allowedUsers>
				<userInRole name="Responsable"/>
			</allowedUsers>
			<consequences>
				<consequence>
					<set state="Acceptee"/>
					<notify message="Votre demande de congés a été accepté. Cependant, elle doit encore être validée !">
						<relatedUser participant="Demandeur"/>
					</notify>
				</consequence>
			</consequences>
		</action>

		<action name="Refuser" form="refus">
			<label>Refuser</label>
			<allowedUsers>
				<userInRole name="Responsable"/>
			</allowedUsers>
			<consequences>
				<consequence>
					<set state="Refusee"/>
				</consequence>
			</consequences>
		</action>

		<action name="Valider" form="validation">
			<label>Valider</label>
			<allowedUsers>
				<userInRole name="Secretaire"/>
			</allowedUsers>
			<consequences>
				<consequence>
					<set state="Traitee"/>
				</consequence>
			</consequences>
		</action>

		<action name="Supprimer" kind="delete">
			<label>Supprimer</label>
			<allowedUsers>
				<relatedUser participant="Demandeur"/>
			</allowedUsers>
			<consequences>
				<consequence>
					<kill>true</kill>
				</consequence>
			</consequences>
		</action>

	</actions>

	<!-- DEFINITION DES FORMULAIRES -->
	<forms>
		<form name="presentationForm">
			<title>Demande de congés</title>
		   <input value="${action.Creation.actor}">
			   <label>Demandeur</label>
			</input>
		   <input item="nature"/>
			<input item="dateDebut" />
			<input item="dateFin" />
			<input item="commentaires" displayerName="textarea"/>
		   <input value="${action.Creation.date}">
			   <label>Demande faite le</label>
			</input>
		   <input value="${instance.state}"/>
		   <input value="${action.Accepter.date}">
			   <label>Congés validés le</label>
			</input>
		   <input value="${action.Accepter.actor}">
			   <label>Responsable</label>
			</input>
		</form>

		<form name="printForm" HTMLFileName="/weblib/processManager/DemandeConges/DemandeConges.html">
		</form>

		<!-- Formulaire de création -->
		<form name="creation">
			<title>Demande de congés</title>
			<input item="nature" mandatory="true"/>
			<input item="duree" />
			<input item="dateDebut" mandatory="true"/>
			<input item="dateFin" mandatory="true"/>
			<input item="commentaires" displayerName="textarea"/>
			<input item="responsable" mandatory="true"/>
			<!--<input item="fichier" mandatory="true"/>-->
		</form>

		<!-- Formulaire de validation du responsable -->
		<form name="acceptation">
			<title>Validation de la demande</title>
		   <input displayerName="textarea"
			       value="des congés du ${folder.dateDebut} au ${folder.dateFin} demandés par ${action.Creation.actor} (service : ${action.Creation.actor.departement})">
			   <label>Acceptation</label>
			</input>
			<input item="commentaires" displayerName="textarea"/>
		</form>

		<!-- Formulaire de refus du responsable -->
		<form name="refus">
			<title>Refus de la demande</title>
		   <input displayerName="textarea"
			       value="des congés du ${folder.dateDebut} au ${folder.dateFin} demandés par ${action.Creation.actor}">
			   <label>Refus</label>
			</input>
			<input item="commentaires" displayerName="textarea"/>
		</form>

		<!-- Formulaire permettant a la secretaire de completer la demande -->
		<form name="validation">
			<title>Validation de la demande</title>
		   <input displayerName="textarea"
			       value="du ${folder.dateDebut} au ${folder.dateFin} demandés par ${action.Creation.actor}">
			   <label>Congés</label>
			</input>
			<input item="nature" mandatory="true"/>
			<input item="duree" />
			<input item="commentaires" displayerName="textarea"/>
		</form>


	</forms>
</processModel>
